---
- name: Delete infrastructure for private cloud in GCP
  hosts: localhost
  connection: local

  vars_files:
  - ~/.apigee-secure/argolis-credentials.yml
  - "{{ playbook_dir | dirname | dirname }}/resources/defaults.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/override.yml"

  collections:
    - bap_coe.gcp_management

  roles:
    - { role: gcp_project_delete }
    - { role: gcp_resource_manager_folders_get_folder_id, when: FOLDER_DISPLAY_NAME is defined }
    - { role: gcp_resource_manager_folders_delete, when: FOLDER_DISPLAY_NAME is defined }
