---
- name: Step 1 - Enable APIs
  hosts: localhost
  connection: local

  vars_files:
  - ~/.apigee-secure/credentials.yml
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-org-host-metadata.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-common-attributes.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-region-{{ DATA_CENTER | default('dc-1') }}.yml"

  vars:
    PROJECT_ID: "{{ APIGEE_HOST_PROJECT_ID }}"
    SERVICE_ACCOUNT_FILE_PATH: "{{ APIGEE_HOST_ADMIN_SERVICE_ACCOUNT_FILE_PATH }}"
  collections:

    - bap_coe.bootstrap_runtime
    - bap_coe.gcp_management

  roles:
    - {
        role: gcp_auth_service_account_activate,
        ADMIN_SERVICE_ACCOUNT: "{{ APIGEE_HOST_ADMIN_SERVICE_ACCOUNT }}",
        CREDENTIALS_DIR: "{{ APIGEE_HOST_CREDENTIALS_DIR }}"
      }
    - {
        role: gcp_project_services_enable,
        tags: ['services'],
        ADMIN_ACCOUNT_EMAIL: "{{ APIGEE_HOST_ADMIN_SERVICE_ACCOUNT }}",
        SERVICE_OP: "enable"
      }

