---
# Project management attribures
TERRAFORM_PROJECT_NAME: x-l7xlb
PROJECT_ID: "friasc-{{ TERRAFORM_PROJECT_NAME | split('-') | join('') }}-202307-26-0945"
TERRAFORM_VAR_FILE: x-demo.tfvars
TERRAFORM_LOG: "DEBUG"
WORK_DIR: "{{ playbook_dir | dirname | dirname }}/work_dir/{{ PROJECT_ID }}"

# Github management attribures.
#GITHUB_REPO_URL: git@github.com:carlosfrias/terraform-modules.git
GITHUB_REPO_URL: https://github.com/apigee/terraform-modules.git
GITHUB_REPO_DEST: "{{ WORK_DIR }}/terraform-projects"

# Terraform management attributes
TERRAFORM_LOG_LEVEL: "DEBUG"
TERRAFORM_PATH_PROJECT: "{{ GITHUB_REPO_DEST }}/samples/{{ TERRAFORM_PROJECT_NAME }}"
TERRAFORM_VAR_FILE_PATH: "{{ TERRAFORM_PATH_PROJECT }}/{{ TERRAFORM_VAR_FILE }}"
TERRAFORM_PATH_BIN_DEST: "{{ TERRAFORM_PATH_PROJECT }}"
TERRAFORM_PATH_BIN: "{{ TERRAFORM_PATH_BIN_DEST }}/terraform"
TERRAFORM_LOG_PATH: "{{ WORK_DIR }}/logs"
TERRAFORM_LOG_FILE_NAME_INIT: "terraform-{{ PROJECT_ID }}-init.log"
TERRAFORM_LOG_FILE_NAME_INIT_PATH: "{{ TERRAFORM_LOG_PATH }}/{{ TERRAFORM_LOG_FILE_NAME_INIT }}"
TERRAFORM_LOG_FILE_NAME_PLAN: "terraform-{{ PROJECT_ID }}-plan.log"
TERRAFORM_LOG_FILE_NAME_PLAN_PATH: "{{ TERRAFORM_LOG_PATH }}/{{ TERRAFORM_LOG_FILE_NAME_PLAN }}"
TERRAFORM_LOG_FILE_NAME_APPLY: "terraform-{{ PROJECT_ID }}-apply.log"
TERRAFORM_LOG_FILE_NAME_APPLY_PATH: "{{ TERRAFORM_LOG_PATH }}/{{ TERRAFORM_LOG_FILE_NAME_APPLY }}"
TERRAFORM_LOG_FILE_NAME_DESTROY: "terraform-{{ PROJECT_ID }}-destroy.log"
TERRAFORM_LOG_FILE_NAME_DESTROY_PATH: "{{ TERRAFORM_LOG_PATH }}/{{ TERRAFORM_LOG_FILE_NAME_DESTROY }}"

GCP_ZONE: us-east1-b
GCP_REGION: us-east1

GCLOUD_ORG_ROLE_BINDINGS:
- "roles/owner"
- "roles/billing.admin"
- "roles/billing.projectManager"
- "roles/iam.serviceAccountAdmin"
- "roles/iam.serviceAccountKeyAdmin"
- "roles/resourcemanager.projectIamAdmin"
- "roles/resourcemanager.organizationAdmin"
- "roles/serviceusage.serviceUsageAdmin"
- "roles/serviceusage.apiKeysAdmin"
- "roles/iap.tunnelResourceAccessor"

GCLOUD_ORG_POLICIES_CONSTRAINTS_ENFORCEMENT_DISABLE:
- constraints/iam.disableServiceAccountKeyCreation
- constraints/iam.disableServiceAccountCreation
- constraints/compute.requireShieldedVm
- constraints/compute.requireOsLogin
- constraints/compute.skipDefaultNetworkCreation

GCLOUD_ORG_POLICIES_UPDATE:
- constraints/compute.trustedImageProjects
- constraints/compute.restrictSharedVpcSubnetworks
- constraints/compute.restrictSharedVpcHostProjects
- constraints/compute.restrictVpcPeering
- constraints/compute.vmExternalIpAccess
- constraints/compute.vmCanIpForward

GCLOUD_PROJECT_SERVICES:
- "compute.googleapis.com"
- "apigee.googleapis.com"
- "servicenetworking.googleapis.com"
- "cloudresourcemanager.googleapis.com"
- "serviceusage.googleapis.com"
- "iam.googleapis.com"
- "iamcredentials.googleapis.com"
- "apigeeconnect.googleapis.com"
#- "dns.googleapis.com"
#- "cloudkms.googleapis.com"
#- "sourcerepo.googleapis.com"
#- "container.googleapis.com"
#- "containerregistry.googleapis.com"
#- "stackdriver.googleapis.com"
#- "meshca.googleapis.com"
#- "meshtelemetry.googleapis.com"
#- "meshconfig.googleapis.com"
#- "anthos.googleapis.com"
#- "gkeconnect.googleapis.com"
#- "gkehub.googleapis.com"
#- "cloudbuild.googleapis.com"
#- "secretmanager.googleapis.com"
#- "pubsub.googleapis.com"
#- "monitoring.googleapis.com"
#- "logging.googleapis.com"
#- "cloudtrace.googleapis.com"
#- "privateca.googleapis.com"


# Attributes to be set in a protected credentials file not stored with scripts
#ADMIN_ACCOUNT_USER: "PROVIDED_IN_CREDENTIALS_YML"
#GCLOUD_ORG_DOMAIN: "PROVIDED_IN_CREDENTIALS_YML"
#BILLING_ID: "PROVIDED_IN_CREDENTIALS_YML"
#GCLOUD_ORG_ID: "PROVIDED_IN_CREDENTIALS_YML"

# SERVICE_ACCOUNT_PROTECTED_VALUES in credentials.yml
ADMIN_ACCOUNT_EMAIL: "{{ ADMIN_ACCOUNT_USER }}@{{ GCLOUD_ORG_DOMAIN }}"
ADMIN_ACCOUNT_EMAIL: "{{ ADMIN_ACCOUNT_USER }}@{{ GCLOUD_ORG_DOMAIN }}"
BILLING_USER_NAME: "{{ ADMIN_ACCOUNT_USER }}"
BILLING_USER_EMAIL: "{{ BILLING_USER_NAME }}@{{ GCLOUD_ORG_DOMAIN }}"
ADMIN_SERVICE_ACCOUNT_NAME: "{{ ADMIN_ACCOUNT_USER }}-service-account"
ADMIN_SERVICE_ACCOUNT_EMAIL: "{{ ADMIN_SERVICE_ACCOUNT_NAME }}@{{ PROJECT_ID }}.iam.gserviceaccount.com"
ADMIN_ACCOUNT_USER: "{{ ADMIN_ACCOUNT_USER }}"
ADMIN_ACCOUNT_EMAIL: "{{ ADMIN_ACCOUNT_USER }}@{{ GCLOUD_ORG_DOMAIN }}"

SERVICE_ACCOUNT_FILE_SUFFIX: "service-account-key"

#  Configure project admin role bindings
GCLOUD_PROJECT_ADMIN_ROLE_BINDINGS:
- "roles/resourcemanager.projectDeleter"
- "roles/resourcemanager.projectCreator"

GCLOUD_PROJECT_SERVICE_ACCOUNT_ROLE_BINDINGS:
- "roles/owner"
- "roles/compute.admin"
- "roles/compute.networkAdmin"
- "roles/compute.instanceAdmin"
- "roles/apigee.admin"
- "roles/networkmanagement.admin"
- "roles/cloudkms.admin"
- "roles/networkmanagement.viewer"
- "roles/iam.serviceAccountAdmin"
- "roles/iam.serviceAccountUser"
- "roles/iam.serviceAccountCreator"
- "roles/iam.serviceAccountKeyAdmin"
#- "roles/compute.loadBalancerAdmin"
