---
- name: Apigee Runtime Configure org policies
  hosts: localhost
  connection: local

  vars_files:
  - ~/.apigee-secure/credentials.yml
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-org-host-metadata.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-common-attributes.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-region-{{ DATA_CENTER | default('dc-1') }}.yml"

  vars:
    PROJECT_ID: "{{ APIGEE_RUNTIME_PROJECT_ID }}"
    WORK_DIR: "{{ APIGEE_RUNTIME_WORK_DIR }}"

  collections:
  - bap_coe.gcp_management
  - bap_coe.bootstrap_runtime

  roles:
  - {
      role: gcp_iam_policy_bindings_org,
      BINDING_OP: "add",
      ROLE_BINDINGS: [
        "{{ GCLOUD_ORG_ROLE_BINDINGS }}",
        "{{ GCLOUD_FOLDER_ROLE_BINDINGS }}",
        "{{ ADMIN_SERVICE_ACCOUNT_ROLE_BINDINGS }}"
      ]
    }
  - { role: gcp_resource_manager_constraints_disable_enforce }
  - { role: gcp_resource_manager_update_org_policy }

