---
- name: Assert credentials folder - {{ chart }}
  file:
    path: "{{ APIGEE_HYBRID_HELM_CHARTS_DIR }}/{{ chart }}"
    state: directory

#- name: Distribute service account authorization file to helm chart folders - {{ chart }}
#  copy:
#    force: true
#    src: "{{ SERVICE_ACCOUNT_FILE_PATH }}"
#    dest: "{{ APIGEE_HYBRID_HELM_CHARTS_DIR }}/{{ chart }}/{{ APIGEE_ADMIN_SERVICE_ACCOUNT_FILE_PATH | basename }}"

- name: Distribute Apigee hybrid overrides - {{ chart }}
  copy:
    force: true
    src: "{{ OVERRIDE_FILE }}"
    dest: "{{ APIGEE_HYBRID_HELM_CHARTS_DIR }}/{{ chart }}/{{ OVERRIDE_FILE | basename }}"
