---
- name: Update molecule variables
  hosts: localhost
  connection: local

  vars_files:
  - ~/.apigee-secure/argolis-credentials.yml
  - "{{ playbook_dir | dirname | dirname }}/resources/defaults.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/override.yml"

  vars:
    file_name: "{{ playbook_dir | dirname | dirname }}/.env.yml"

  tasks:
  - name: Remove molecule .env.yml
    file:
      path: "{{ file_name }}"
      state: absent
