---
- name: Apigee Runtime Install Apigee Ingress Manager
  hosts: localhost
  connection: local
  gather_facts: true
  environment:
    ENABLE_TURBO_MODE: 1

  vars_files:
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-org-host-metadata.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-common-attributes.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-region-{{ DATA_CENTER | default('dc-1') }}.yml"

  vars:
    OVERRIDE_FILE: "{{ APIGEE_RUNTIME_OVERRIDE_FILE }}"

  tasks:
    - block:
      - name: Install Apigee Ingress Manager
        kubernetes.core.helm:
          state: present
          chart_ref: "{{ APIGEE_HYBRID_HELM_CHARTS_DIR }}/apigee-ingress-manager"
          namespace: "{{ APIGEE_NAMESPACE }}"
          name: ingress-manager
          create_namespace: true
          wait_timeout: "{{ HELM_BINARY_TIMEOUT }}"
          binary_path: "{{ HELM_BINARY }}"
          values_files:
          - "{{ APIGEE_HYBRID_HELM_CHARTS_DIR }}/apigee-ingress-manager/{{ OVERRIDE_FILE | basename }}"

      rescue:

        - name: RESCUE - Install Apigee Ingress Manager - debug
          kubernetes.core.helm:
            binary_path: "{{ HELM_BINARY }} --debug "
            state: present
            chart_ref: "{{ APIGEE_HYBRID_HELM_CHARTS_DIR }}/apigee-ingress-manager"
            namespace: "{{ APIGEE_NAMESPACE }}"
            name: ingress-manager
            create_namespace: true
            wait_timeout: "{{ HELM_BINARY_TIMEOUT }}"
            values_files:
            - "{{ APIGEE_HYBRID_HELM_CHARTS_DIR }}/apigee-ingress-manager/{{ OVERRIDE_FILE | basename }}"
