---
- name: Config Apigee Redis
  hosts: localhost
  connection: local
  gather_facts: true
  environment:
    ENABLE_TURBO_MODE: 1

  vars_files:
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-metadata.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-common-attributes.yml"
  tasks:
  - name: Uninstall Apigee Redis
    kubernetes.core.helm:
      state: absent
      chart_ref: "{{ APIGEE_HYBRID_HELM_CHARTS_DIR }}/apigee-redis"
      namespace: "{{ APIGEE_NAMESPACE }}"
      name: redis
