---
- name: CApigee Runtime onfigure Apigee Operator CRDs
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
  - ~/.apigee-secure/credentials.yml
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-org-host-metadata.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-common-attributes.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-region-{{ DATA_CENTER | default('dc-1') }}.yml"



  tasks:
    - name: Apply Apigee Operator CRDs
      shell: |
        kubectl apply -k  apigee-operator/etc/crds/default/ \
          --server-side \
          --force-conflicts \
          --validate=false
      args:
        chdir: "{{ APIGEE_HYBRID_HELM_CHARTS_DIR }}"

    - name: Collect Apigee Operator CRDs installation status
      shell: kubectl get crds | grep apigee
      register: validate

#    - name: Validate Apigee Operator CRDs
#      assert:
#        that:
#        - "{{ item }} in ' {{ validate.stdout }}'"
#      loop:
#      - "apigeedatastores"
#      - "apigeedeployments"
#      - "apigeeenvironments"
#      - "apigeeissues"
#      - "apigeeorganizations"
#      - "apigeeredis"
#      - "apigeerouteconfigs"
#      - "apigeeroutes"
#      - "apigeetelemetries"
#      - "cassandradatareplications"

#    - name: DOES NOT WORK - Apply CRDs use command line
#      kubernetes.core.k8s:
#        state: present
#        src: "{{ APIGEE_HYBRID_HELM_CHARTS_DIR }}/apigee-operator/etc/crds/default/kustomization.yaml"
#        name: apigeedeployment
#        namespace: "{{ APIGEE_NAMESPACE }}"
#        validate:
#          fail_on_error: false
#        server_side_apply:
#          field_manager: kubectl
#          force_conflicts: true
#        continue_on_error: true
