- name: Create DNS record
  hosts: localhost
  connection: local

  vars_files:
  - ~/.apigee-secure/credentials.yml
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-org-host-metadata.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-common-attributes.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-region-{{ DATA_CENTER | default('dc-1') }}.yml"

  collections:
    - bap_coe.apigee_hybrid
    - bap_coe.gcp_management

  vars:
    PROJECT_ID: "{{ APIGEE_RUNTIME_PROJECT_ID }}"
    GCP_TOKEN_FILE_PATH: "{{ APIGEE_HOST_GCP_TOKEN_FILE_PATH }}"

  roles:
  - { role: gce_external_ip_get }
  - {
      role: apigee-hybrid-cloud-dns-create,
      FQ_DOMAIN_NAME: "{{ DOMAIN_NAME }}"
    }
