---
#- name: Set data center
#  hosts: localhost
#  connection: local
#  gather_facts: true
#
#  tasks:
#  - name: Set data center fact
#    set_fact:
#      cacheable: true
#      DATA_CENTER: "dc-1"

- name: Remove Apigee Runtime DNS record
  hosts: localhost
  connection: local

  vars_files:
  - ~/.apigee-secure/credentials.yml
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-org-host-metadata.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-common-attributes.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-region-{{ DATA_CENTER | default('dc-1') }}.yml"

  vars:
    PROJECT_ID: "{{ APIGEE_RUNTIME_PROJECT_ID }}"
    GCP_TOKEN_FILE_PATH: "{{ APIGEE_HOST_GCP_TOKEN_FILE_PATH }}"

  collections:
    - bap_coe.apigee_hybrid
    - bap_coe.gcp_management

  roles:
  - {
      role: apigee-hybrid-cloud-dns-delete,
      FQ_DOMAIN_NAME: "{{ DOMAIN_NAME }}"
    }

