---
- name: Create Apigee host service accounts before enabling apis
  hosts: localhost
  connection: local

  vars_files:
  - ~/.apigee-secure/credentials.yml
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-org-host-metadata.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-common-attributes.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-region-{{ DATA_CENTER | default('dc-1') }}.yml"

  vars:
    PROJECT_ID: "{{ APIGEE_CONTROL_PROJECT_ID }}"
    WORK_DIR: "{{ APIGEE_CONTROL_WORK_DIR }}"
    SERVICE_ACCOUNT_EMAIL: "{{ APIGEE_CONTROL_ADMIN_SERVICE_ACCOUNT }}"
    SERVICE_ACCOUNT_FILE_PATH: "{{ APIGEE_CONTROL_ADMIN_SERVICE_ACCOUNT_FILE_PATH }}"
    PROJECT_SERVICE_ACCOUNT_FQ_NAME_SUFFIX: "{{ APIGEE_CONTROL_PROJECT_SERVICE_ACCOUNT_FQ_NAME_SUFFIX }}"
    TIME_TO_PROPAGATE_BINDINGS: 20

  collections:
    - bap_coe.gcp_management
    - bap_coe.bootstrap_runtime

  roles:
  - {
      role: gcp_iam_service_account_mgmt,
      SERVICE_OP: 'create',
      SERVICE_ACCOUNTS: "{{ APIGEE_SERVICE_ACCOUNTS }}"
    }
  - {
      role: gcp_iam_service_account_key_generation,
      KEY_FILE_PATH: "{{ APIGEE_CONTROL_CREDENTIALS_DIR }}",
      SERVICE_ACCOUNTS: "{{ APIGEE_SERVICE_ACCOUNTS }}"
    }
  - {
      role: service_account_file_path,
      KEY_FILE_PATH: "{{ APIGEE_CONTROL_CREDENTIALS_DIR }}"
    }
  - {
      role: service_account_file_processing,
      SERVICE_ACCOUNT_FILE_PATH: "{{ APIGEE_CONTROL_ADMIN_SERVICE_ACCOUNT_FILE_PATH }}"
    }
  - {
      role: gcp_auth_service_account_activate,
      ADMIN_SERVICE_ACCOUNT: "{{ APIGEE_CONTROL_ADMIN_SERVICE_ACCOUNT_FILE_PATH }}"
    }
  - {
      role: gcp_iam_policy_bindings,
      BINDING_OP: "add",
      ACCOUNT_TYPE: "serviceAccount",
      POLICY_BINDINGS: "{{ ADMIN_SERVICE_ACCOUNT_ROLE_BINDINGS }}"
    }

