---
- name: Provision project - destroy invocation
  import_playbook: "{{ playbook_dir | dirname }}/provision-project-control/destroy.yml"


- name: Clean up Apigee hybrid filesystem
  hosts: localhost
  connection: local
  gather_facts: true
  environment:
    ENABLE_TURBO_MODE: 1

  vars_files:
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-org-host-metadata.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-common-attributes.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-region-{{ DATA_CENTER | default('dc-1') }}.yml"

  vars:
    WORK_DIR: "{{ APIGEE_HOST_WORK_DIR }}"

  tasks:
  - name: Clean up work_dir
    file:
      path: "{{ WORK_DIR }}"
      state: absent

