---
GCP_REGION: "us-east1"
GCP_ZONE_LOCATION: "d"
GCP_ZONE: "{{ GCP_REGION }}-{{ GCP_ZONE_LOCATION }}"
REGION: "{{ GCP_REGION }}"
ZONE: "{{ GCP_ZONE }}"
REGION_SEED: "{{ GCP_REGION }}"

# Cluster Name and Cluster Zone
CLUSTER_SEED: 1
CLUSTER_COUNT: 1
CLUSTER_NAME_PREFIX: "apigee-hybrid"
CLUSTER_NAME: "{{ CLUSTER_NAME_PREFIX }}-{{ CLUSTER_COUNT }}"
CLUSTER_ZONE: "{{ REGION }}-{{ GCP_ZONE_LOCATION }}"
FQ_CLUSTER_NAME: "gke_{{ APIGEE_HOST_PROJECT_ID }}_{{ CLUSTER_ZONE }}_{{ CLUSTER_NAME }}"
CLUSTER_REGION: "{{ REGION }}"
CLUSTER_CHANNEL: "stable"  # can be one of rapid, regular, stable, or None.

CASSANDRA_HOST_NETWORK: True
