---
collections:
  - name: google.cloud
  - name: community.google
  - name: community.general.facter
  - name: git+https://github.com/carlosfrias/apigee-hybrid-workspace.git#bap_coe/gcp_management,master
  - name: git+https://github.com/carlosfrias/apigee-hybrid-workspace.git#bap_coe/performance_testing,master
  - name: git+https://github.com/carlosfrias/apigee-hybrid-workspace.git#bap_coe/apigee_hybrid,master
  - name: git+https://github.com/carlosfrias/apigee-hybrid-workspace.git#bap_coe/bastion_host,master
  - name: git+https://github.com/carlosfrias/apigee-hybrid-workspace.git#bap_coe/bootstrap_runtime,master
  - name: git+https://github.com/carlosfrias/apigee-hybrid-workspace.git#bap_coe/private_cloud,master
